### ISSUE TITLE
Monocle 21 builds available

### ISSUE THREAD

**Issue by FlorianKirmaier** [TestFX/Monocle#99]
Hi everyone,

I was checking Test/Monocle, and the latest build was for 12.
So, I'm not sure of the state of the monocle libraries, but I assumed the repository to be dead, and created own builds.
I also published them on Maven Central:
https://github.com/sandec/monocle
https://repo.maven.apache.org/maven2/one/jpro/openjfx-monocle/jfx-21/

It is a drop-in replacement.
```
<dependency>
  <groupId>one.jpro</groupId>
  <artifactId>openjfx-monocle</artifactId>
  <version>jfx-21</version>
</dependency>
```

**Comment by karianna** [comment]
Thank you for this!  We're trying it out now for PCGen.

**Comment by gmseed** [comment]
Hi

I was interested in this plugin because I have a Java8 JavaFX/TestFX Maven project that uses surefire and sets "testfx.headless" to true. It worked fine until we found on one developer's machine a monocle/glass issue. And so we added the added the "openjfx-monocle" 8u76-b04 test dependency, which resolved running he TestFX tests.

Now, in migrating our Java8 project to Java21, I see that in Maven central the "openjfx-monocle" dependency stops at Java12. And so I stumbled on this post. I added the above one.jpro/openjfx-monocle Java21 dependency but are seeing a lot of command-line errors when I run mvn package/mvn test.

Errors such as:

Caused by: java.lang.IllegalAccessError: class com.sun.glass.ui.monocle.NativePlatform (in unnamed module @0x510f3d34) cannot access class com.sun.javafx.util.Logging (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.util to unnamed module @0x510f3d34
        at com.sun.glass.ui.monocle.NativePlatform.<init>(NativePlatform.java:42)
        at com.sun.glass.ui.monocle.HeadlessPlatform.<init>(HeadlessPlatform.java:28)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)

and so I added the following as an argLine option in the "org.apache.maven.plugins" plugin:

--add-opens javafx.graphics/com.sun.javafx.util=ALL-UNNAMED

I then get the error:

java.lang.IllegalAccessError: class com.sun.glass.ui.monocle.NativePlatform (in unnamed module @0x510f3d34) cannot access class com.sun.javafx.logging.PlatformLogger$Level (in module javafx.base) because module javafx.base does not export com.sun.javafx.logging to unnamed module @0x510f3d34
        com.sun.glass.ui.monocle.NativePlatform.logSelectedCursor(NativePlatform.java:198)
        com.sun.glass.ui.monocle.HeadlessPlatform.createCursor(HeadlessPlatform.java:39)
        com.sun.glass.ui.monocle.NativePlatform.getCursor(NativePlatform.java:116)
        com.sun.glass.ui.monocle.MouseInput.setState(MouseInput.java:130)
        com.sun.glass.ui.monocle.MonocleApplication.staticScreen_getScreens(MonocleApplication.java:240)
        javafx.graphics@21/com.sun.glass.ui.Screen.initScreens(Screen.java:410)
        javafx.graphics@21/com.sun.glass.ui.Application.lambda$run$1(Application.java:154)
        com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        java.base/java.lang.Thread.run(Thread.java:1583)

and don't seem to be able to get to the bottom of the errors.

Any suggestions would be gratefully appreciated.
Thanks.

**Comment by iriikoad** [comment]
Hi, I found also this repo:

https://github.com/sebivenlo/testfx-monocle

the JARs are on central: https://mvnrepository.com/artifact/io.github.sebivenlo/openjfx-monocle/jdk-21.0.1

**Comment by mvsoder** [comment]
Monocle 21 builds coming soon.

**Comment by mvsoder** [comment]
A Monocle 21 build has now been posted: https://central.sonatype.com/artifact/org.testfx/openjfx-monocle
